### ISSUE TITLE
Cannot get a valid BOARD ?

### ISSUE THREAD

**Issue by Salamandar** [tohara/marlin-cmake#1]
I'm trying to build Marlin with this, but I can't get the Toolchain file to accept any board ID.

For now my CMakeLists.txt is :

```
####################################################################
#   Project configuration
####################################################################
cmake_minimum_required(VERSION 3.0)

set(CMAKE_TOOLCHAIN_FILE ${CMAKE_SOURCE_DIR}/cmake/toolchain/ArduinoToolchain.cmake)

project (Marlin-Triforce)
set     (Marlin-Triforce_VERSION_MAJOR 0)
set     (Marlin-Triforcre_VERSION_MINOR 9)

set(Marlin_SKETCH ${CMAKE_SOURCE_DIR})

set(Marlin_BOARD mega)

generate_arduino_firmware(Marlin)
```

I just cloned this repo as the `cmake` directory.
Why doesn't this work ?

**Comment by tohara** [comment]
You need to include the Arduino_SDK module to find the SDK install path, and you need to specify the CPU for the mega board. 

I am not sure why, but using SKETCH does not work, try change it to using SRCS instead.
I have tested with a CMakeLists.txt as show below and I get it to compile.

```
####################################################################
#   Project configuration
####################################################################
cmake_minimum_required(VERSION 3.0)

set(CMAKE_MODULE_PATH  ${CMAKE_MODULE_PATH} ${CMAKE_SOURCE_DIR}/cmake/modules)

include(Arduino_SDK) # Find the intallpath of Arduino SDK

set(CMAKE_TOOLCHAIN_FILE ${CMAKE_SOURCE_DIR}/cmake/toolchain/ArduinoToolchain.cmake)


project (Marlin-Triforce)
set     (Marlin-Triforce_VERSION_MAJOR 0)
set     (Marlin-Triforcre_VERSION_MINOR 9)

#set(Marlin_SKETCH ${CMAKE_SOURCE_DIR})

file(GLOB SOURCES "*.cpp")
set(Marlin_SRCS "${SOURCES};Marlin.ino")

set(Marlin_BOARD mega)
set(Marlin_CPU atmega2560)

generate_arduino_firmware(Marlin)
```

I have also provided two CMakeLists.txt files that can be used for marlin and will read the correct board configuration from Configuration.h.

To use this you just need to copy CMakelists/MarlinRootDir/CMakeLists.txt to the root (Marlin-Triforce in your case) directory and copy CMakelists/MarlinSrcDir/CMakeLists.txt to the source( Marlin) directory.

Then from the root directory run:
mkdir build && cd build
cmake ..
make

The needed toolchain files will the be downloaded to the build directory.

For some more info see: https://github.com/MarlinFirmware/Marlin/issues/4680

**Comment by Salamandar** [comment]
Okay, then the README is not really clear about that ;)
That works, well I can't get it to compile because I need to include the U8Glib library but that's another problem.
